# API ci
variables:
  SERVICE_NAME: "docs"
stages:
  - deploy_staging
  - deploy_production

deploy_staging:
  stage: deploy_staging
  image: google/cloud-sdk:latest
  only:
    - staging
  script:
    - echo $GCP_SERVICE_ACCOUNT_STAGING > gcloud-service-key.json 
    - gcloud auth activate-service-account --key-file gcloud-service-key.json 
    - gcloud auth configure-docker 
    - gcloud config set gcloudignore/enabled false
    - gcloud config set project $GCP_PROJECT_ID_STAGING 
    - gcloud config set builds/use_kaniko True
    - gcloud config set builds/kaniko_cache_ttl 240
    - gcloud builds submit --timeout=900s --tag gcr.io/$GCP_PROJECT_ID_STAGING/$SERVICE_NAME 
    - gcloud run deploy --port=9000 $SERVICE_NAME --image gcr.io/$GCP_PROJECT_ID_STAGING/$SERVICE_NAME --region=us-central1 --platform managed --allow-unauthenticated

deploy_prod:
  stage: deploy_production
  image: google/cloud-sdk:latest
  only:
    - master  
  script:
    - echo $GCP_SERVICE_ACCOUNT_PROD > gcloud-service-key.json 
    - gcloud auth activate-service-account --key-file gcloud-service-key.json 
    - gcloud auth configure-docker 
    - gcloud config set gcloudignore/enabled false
    - gcloud config set project $GCP_PROJECT_ID_PROD 
    - gcloud builds submit --timeout=900s --tag  gcr.io/$GCP_PROJECT_ID_PROD/$SERVICE_NAME 
    - gcloud run deploy --port=80 $SERVICE_NAME --image gcr.io/$GCP_PROJECT_ID_PROD/$SERVICE_NAME --region=us-central1 --platform managed --allow-unauthenticated
